// -------------------------------------------------------------
//
// File Name: hdlsrc\pos_edge.v
// Created: 2012-11-30 18:34:25
// Generated by MATLAB 7.6 and Simulink HDL Coder 1.3
//
//
// -------------------------------------------------------------


// -------------------------------------------------------------
//
// Module: pos_edge
// Source Path: fofb_multi_ram_sel_sim/pos_edge
// Hierarchy Level: 1
//
//
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pos_edge
          (
           clk,
           reset,
           enb,
           trig_in,
           trig_out
          );


  input   clk;
  input   reset;
  input   enb;
  input   trig_in;
  output  trig_out;


  wire Logical_Operator_out1;
  reg  Integer_Delay_out1;
  wire Logical_Operator2_out1;

  assign Logical_Operator_out1 = !trig_in;

  always @ (posedge clk or posedge reset)
    begin: Integer_Delay_process
      if (reset == 1'b1) begin
        Integer_Delay_out1 <= 0;
      end
      else begin
        if (enb == 1'b1) begin
          Integer_Delay_out1 <= Logical_Operator_out1;
        end
      end
    end // Integer_Delay_process

  assign Logical_Operator2_out1 =  trig_in & Integer_Delay_out1;

  assign trig_out = Logical_Operator2_out1;

endmodule  // pos_edge

