// -------------------------------------------------------------
//
// File Name: hdlsrc\nm_sub.v
// Created: 2013-05-11 11:31:54
// Generated by MATLAB 7.6 and Simulink HDL Coder 1.3
//
//
// -------------------------------------------------------------

// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nm_sub
          (
           clk,
           reset,
           clk_enable,
           pos_in_nm_i,
           ref_in_nm_i,
           Kn_s32_31b_i,	//mm gain :2.1475e+003, for mm unit:  (0.000001*2^31) = hex
           //
           nm_err_s32_o,
           err_s32_24b_o,
           err_reg_s32_24b_o
          );


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] pos_in_nm_i;  // int32
  input   signed [31:0] ref_in_nm_i;  // int32
  input   signed [31:0] Kn_s32_31b_i;  // sfix32_En31
  //output  ce_out;
  output  signed [31:0] nm_err_s32_o;  // int32
  output  signed [31:0] err_s32_24b_o;  // sfix32_En24
  output  signed [31:0] err_reg_s32_24b_o;  // sfix32_En24


  wire enb;
  wire enb_1_1_1;
  wire signed [32:0] Sub_out1;  // sfix33
  wire signed [31:0] conv_out1;  // int32
  wire signed [31:0] mult_out1;  // sfix32_En24
  reg signed [31:0] Integer_Delay_out1;  // sfix32_En24
  wire signed [32:0] sub_cast;  // sfix33
  wire signed [32:0] sub_cast_1;  // sfix33
  wire signed [33:0] sub_temp;  // sfix34
  wire signed [32:0] conv_tmp;  // sfix33
  wire signed [63:0] mul_temp;  // sfix64_En31

  assign enb_1_1_1 = clk_enable;
  //assign ce_out = enb_1_1_1;
  assign sub_cast = $signed({{1{ref_in_nm_i[31]}}, ref_in_nm_i});
  assign sub_cast_1 = $signed({{1{pos_in_nm_i[31]}}, pos_in_nm_i});
  assign sub_temp = sub_cast - sub_cast_1;
  assign Sub_out1 = sub_temp[32:0];

  assign conv_tmp = Sub_out1;

  assign conv_out1 = (conv_tmp[32] == 1'b0 & conv_tmp[31] != 1'b0) ? 32'b01111111111111111111111111111111 : 
      (conv_tmp[32] == 1'b1 && conv_tmp[31] != 1'b1) ? 32'b10000000000000000000000000000000 : conv_tmp[31:0];

	  
  assign nm_err_s32_o = (clk_enable == 1'b1) ? conv_out1 : 32'h7fffffff;    //0;
  
  assign mul_temp = conv_out1 * Kn_s32_31b_i;
  assign mult_out1 = $signed({mul_temp[38:7]} + (mul_temp[63] & |mul_temp[6:0]));

  assign err_s32_24b_o = mult_out1;
  always @ (posedge clk or posedge reset)
    begin: Integer_Delay_process
      if (reset == 1'b1) begin
        Integer_Delay_out1 <= 0;
      end
      else begin
        if (enb == 1'b1) begin
          Integer_Delay_out1 <= mult_out1;
        end
      end
    end // Integer_Delay_process

  assign err_reg_s32_24b_o = Integer_Delay_out1;
  assign enb = clk_enable;

endmodule  // nm_sub

